services:

  mariadb:
    image: mariadb:bmoudach
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
      - .env
    networks :
      - inception
    restart: always

  nginx:
    image: nginx:bmoudach
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always

  wordpress:
    image: wordpress:bmoudach
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file :
      - .env
    networks:
      - inception
    restart: always

networks:
  inception:
    name: inception

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/bmoudach/data/mariadb
      o : bind
      type : none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/bmoudach/data/wordpress
      o : bind
      type : none